### ISSUE TITLE
Not opening preview.pdf

### ISSUE THREAD

**Issue by mprevot** [ajshort/vscode-latex-preview#12]
At each saving / update, the compilation occurs there:
AppData\Local\Temp\tmp-1912AbXY3Tgja2w1\preview.pdf

But nothing is displayed in the preview windows (since recent vscode update, 1.9.0 date 20017-01-27T10:46:43.625Z)

**Comment by czifro** [comment]
I am having a similar issue. It appears that it compiles everything alright, its just the preview window does not open it. I also am using vscode 1.9.0 2017-02-02T08:21:04.221Z on macOS

**Comment by ajshort** [comment]
Thanks for the reports :) Unfortunately I don't have time at the moment to chase this down, it might have to wait for a week or two.

**Comment by Elliot2560** [comment]
I having a similar issue on Linux. I am using VS Code 1.9.0 on Arch Linux. Just thought I should comment to point out that this issue is not specific to macOS.

**Comment by Elliot2560** [comment]
I tried my best to hunt down the issue and provide some insight to the source of the problem. Unfortunately I am not very familiar with web programming these days, so this is as far as I can get. 
I made the `provideTextDocumentContent` method in `document.ts` print the return value to a file, and loaded the file through chrome. The following error is thrown:
`XMLHttpRequest cannot load file:///tmp/tmp-30448PeD1UuPe02HC/preview.pdf. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.`
If I reload the file in chrome with the `--allow-file-access-from-files` option on, the page actually loads without issue, and syncs with the .tex file as expected. I suspect something changed with the security settings of vscode in the latest update and caused the issue.
Hope this helps.

**Comment by eriknstevenson** [comment]
Experiencing a similar issue here on Ubuntu 16 with Visual Studio Code 1.9.0. The problem *seemed* to begin after the recent new release of Code.

**Comment by mprevot** [comment]
Yes, same for me. It happened after a release.

M

**Comment by ajshort** [comment]
Thanks @Elliot2560. It looks like I will have to serve the PDF file through the HTTP server rather than requesting directly from the file system. Hopefully I will get to it sometime this week.

**Comment by ivan-bocharov** [comment]
Hi @ajshort, I experienced the same issues while being on 1.9.0. However, after updating the editor to 1.9.1 today, I am again able to render the preview in the editor.

**Comment by mprevot** [comment]
Same here. Resolved with the vscode update .

Cheers

2017-02-09 11:16 GMT+01:00 Ivan Bocharov <notifications@github.com>:

**Comment by ajshort** [comment]
Awesome! I have confirmed it is working with 1.9.1 as well. Thanks everyone for the reports.
