### ISSUE TITLE
Unable to Create Build Task for basic file

### ISSUE THREAD

**Issue by Zyian** [ajshort/vscode-latex-preview#13]
There's an issue when trying to create a build task for any LaTeX file. Selecting the command pops up with the error. "Cannot read property 'map' of undefined"

Things I've tried:
Clean install VSCode
Clean install BasicTex

I tried to check the settings file to see if I'm missing a setting but I could not find anything related.

**Comment by ajshort** [comment]
Thanks for the report! Unfortunately I can't replicate this.

1. Which version of VSCode are you running?
2. Are there any `.tex` files in your workspace?
